apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrixapps
  namespace: ingress-basic
  labels:
    app: nutrixapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutrixapps
  template:
    metadata:
      labels:
        app: nutrixapps
    spec:
      containers:
        - name: nutrixapps
          image: nutrix.azurecr.io/nutrix-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080