# Generated by Django 3.2.13 on 2022-07-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_nutritionlogging_meal_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionlogging',
            name='meal_size',
        ),
    ]
