# Generated by Django 3.2.13 on 2022-07-04 09:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('meal_image', models.ImageField(upload_to='meal_logging')),
            ],
        ),
        migrations.CreateModel(
            name='MealLogging',
            fields=[
                ('meal_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SUPPER', 'Supper'), ('OTHER', 'Other')], max_length=20)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('meal_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.mealimage')),
            ],
        ),
    ]
