# Generated by Django 3.2.13 on 2022-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_meallogging_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealimage',
            name='total_calorie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
