# Generated by Django 3.2.13 on 2022-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_mealimage_total_calorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealimage',
            name='meal_size',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
