# Generated by Django 3.2.13 on 2022-08-01 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_auto_20220801_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallogging',
            name='meal_image',
        ),
        migrations.AddField(
            model_name='mealimage',
            name='meal_logging',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meal.meallogging'),
            preserve_default=False,
        ),
    ]
