# Generated by Django 2.2.17 on 2022-05-04 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('food_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('food_type', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodLabel',
            fields=[
                ('food_label_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('food_image_path', models.ImageField(blank=True, default='undraw_profile.svg', null=True, upload_to='img/food', verbose_name='Food Upload')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_label.FoodType')),
            ],
        ),
    ]
