# Generated by Django 2.2.17 on 2022-05-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlabel',
            name='food_image_path',
            field=models.ImageField(blank=True, null=True, upload_to='img/food', verbose_name='Food Upload'),
        ),
    ]
