# Generated by Django 3.2.13 on 2022-07-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_id_account_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='img/undraw_profile.svg', null=True, upload_to='img/profile'),
        ),
    ]
