# Generated by Django 3.2.13 on 2022-07-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220708_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealsetting',
            name='advice',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
