# Generated by Django 3.2.13 on 2022-07-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_mealsetting_advice'),
        ('user', '0006_alter_account_profile_pic'),
    ]

    operations = [
    ]
